services:
  - type: web
    name: url-shortener
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: BASE_URL
        sync: false